In [1]:
#QUESTION 1
#create a class employee.
class Employee:
    #create a datamember to count the no.of employees.
    no_of_employees = 0

    #create a constructor to initialize name,family,salary,department.
    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1


    #create a function to average salary.
    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees
    

#create a fulltime emlpoyee class and it should inherit the properties of Employee class.
class FulltimeEmployee(Employee) :

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("full time employee Benefits.")
    

#create the instances of Fulltime Employee class and employee class and call their member functions.
def main():
    employees = []
    fte1 = FulltimeEmployee("E1", "Family1", 200000, "CSE")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("E2", "Family2", 100000, "IT")
    employees.append(fte2)
    emp1 = Employee("E3", "Family3", 250000, "CIS")
    employees.append(emp1)
    emp2 = Employee("E4", "Family4", 300000, "BD")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()

full time employee Benefits.
Average salary: 212500.0


In [4]:
#QUESTION2 
#create a randomm vector of size 20 having only float in the range 1-20.
import numpy as np
x=np.random.uniform(1,20,20)
print("Original array:")
print(x)
#reshape the array to 4 by 5
x1=x.reshape(4,5)
print("Reshaped Array: ")
print(x1)
#replace the max in each row by 0  (axis=1)
x1[np.arange(len(x1)), x1.argmax(1)]=0
print("Maximum value replaced by 0:")
print(x1)

Original array:
[13.55238491 19.86164059  7.68722113 11.84393326 17.95704448  2.59418807
 13.80231946  3.4973878   4.52880524 16.79038378  8.57295957  5.33979586
  7.58876727 10.48530318 14.5236423   7.36724877  3.77122698 16.85288607
 17.95887903 17.40173068]
Reshaped Array: 
[[13.55238491 19.86164059  7.68722113 11.84393326 17.95704448]
 [ 2.59418807 13.80231946  3.4973878   4.52880524 16.79038378]
 [ 8.57295957  5.33979586  7.58876727 10.48530318 14.5236423 ]
 [ 7.36724877  3.77122698 16.85288607 17.95887903 17.40173068]]
Maximum value replaced by 0:
[[13.55238491  0.          7.68722113 11.84393326 17.95704448]
 [ 2.59418807 13.80231946  3.4973878   4.52880524  0.        ]
 [ 8.57295957  5.33979586  7.58876727 10.48530318  0.        ]
 [ 7.36724877  3.77122698 16.85288607  0.         17.40173068]]
